version: '3'
services:
  ecommerce:
    image: ecommerce
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: ecommerce
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
